os: windows
language: csharp
mono: none

script:
- choco install dotnetcore-sdk
- choco install codecov
- dotnet build -c Release
- dotnet test --filter "FullyQualifiedName~UnitTests" -p:CollectCoverage=true -p:CoverletOutputFormat="json%2copencover" -p:CoverletOutput="../coverage" -p:MergeWith="../coverage.json" -c Release --no-build BandwidthMonitorService.sln
- codecov -f "coverage.opencover.xml" -t 75e4b7de-47f2-4190-b814-348a9f1658be