version: '3.4'

services:
  mongodb:
    image: mongo:bionic
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

  bandwidthmonitorservice:
    image: ${DOCKER_REGISTRY-}bandwidthmonitorservice
    container_name: api
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - BWM_MongoDbConnectionString=mongodb://mongo:27017
      - BWM_DownloadBufferSize=1048576
      - BWM_SecondsDelayBeforeFirstSample=10
      - BWM_MinutesBetweenSamples=5
    build:
      context: ../
      dockerfile: BandwidthMonitorService/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network

  bandwidthmonitorservice.portal:
    image: ${DOCKER_REGISTRY-}bandwidthmonitorservice.portal
    container_name: porta
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - BWMP_BandwidthMonitorServiceBaseUrl=http://api:5000
    build:
      context: ../
      dockerfile: BandwidthMonitorService.Portal/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    external: true